"""change storage back to database

Revision ID: 0674eeb11a0c
Revises: 5e355880dfa4
Create Date: 2025-02-04 21:14:25.569020

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0674eeb11a0c'
down_revision = '5e355880dfa4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document_summaries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_content', sa.LargeBinary(length=4294967295), nullable=True))
        batch_op.alter_column('summary_text',
               existing_type=mysql.LONGTEXT(collation='utf8mb4_unicode_ci'),
               type_=sa.Text(length=4294967295),
               existing_nullable=False)
        batch_op.alter_column('original_text',
               existing_type=mysql.LONGTEXT(collation='utf8mb4_unicode_ci'),
               type_=sa.Text(length=4294967295),
               existing_nullable=False)
        batch_op.drop_column('file_path')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document_summaries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_path', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True))
        batch_op.alter_column('original_text',
               existing_type=sa.Text(length=4294967295),
               type_=mysql.LONGTEXT(collation='utf8mb4_unicode_ci'),
               existing_nullable=False)
        batch_op.alter_column('summary_text',
               existing_type=sa.Text(length=4294967295),
               type_=mysql.LONGTEXT(collation='utf8mb4_unicode_ci'),
               existing_nullable=False)
        batch_op.drop_column('file_content')

    # ### end Alembic commands ###
