"""Update summary fields for new parameters

Revision ID: 1fa1c5260270
Revises: 
Create Date: 2025-04-19 10:51:30.759904

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1fa1c5260270'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('search_history', schema=None) as batch_op:
        batch_op.drop_index('idx_user_document')

    op.drop_table('search_history')
    with op.batch_alter_table('system_settings', schema=None) as batch_op:
        batch_op.drop_index('idx_setting_key')
        batch_op.drop_index('setting_key')

    op.drop_table('system_settings')
    with op.batch_alter_table('document_summaries', schema=None) as batch_op:
        batch_op.alter_column('original_text',
               existing_type=mysql.MEDIUMTEXT(collation='utf8mb4_unicode_ci'),
               type_=sa.Text(length=16777215),
               existing_nullable=True)
        batch_op.alter_column('summary_text',
               existing_type=mysql.MEDIUMTEXT(collation='utf8mb4_unicode_ci'),
               type_=sa.Text(length=16777215),
               existing_nullable=True)
        batch_op.alter_column('file_content',
               existing_type=mysql.MEDIUMBLOB(),
               type_=sa.LargeBinary(length=16777215),
               existing_nullable=True)
        batch_op.alter_column('content_vectors',
               existing_type=mysql.MEDIUMBLOB(),
               type_=sa.LargeBinary(length=16777215),
               existing_nullable=True)
        batch_op.alter_column('summary_vectors',
               existing_type=mysql.MEDIUMBLOB(),
               type_=sa.LargeBinary(length=16777215),
               existing_nullable=True)
        batch_op.drop_index('ft_keywords', mysql_prefix='FULLTEXT')
        batch_op.drop_index('ft_summary', mysql_prefix='FULLTEXT')
        batch_op.drop_index('idx_created_at')
        batch_op.drop_index('idx_file_hash')
        batch_op.drop_index('idx_user_id')
        batch_op.drop_constraint('document_summaries_ibfk_1', type_='foreignkey')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('file_chunks', schema=None) as batch_op:
        batch_op.alter_column('chunk_data',
               existing_type=mysql.MEDIUMBLOB(),
               type_=sa.LargeBinary(length=10485760),
               existing_nullable=False)
        batch_op.drop_index('idx_document_chunk')

    with op.batch_alter_table('file_mappings', schema=None) as batch_op:
        batch_op.drop_index('idx_summary_id')
        batch_op.drop_index('idx_system_filename')

    with op.batch_alter_table('summaries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('purpose', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('audience', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('emphasis', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('structure', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('critical', sa.String(length=50), nullable=True))
        batch_op.alter_column('original_text',
               existing_type=mysql.MEDIUMTEXT(collation='utf8mb4_unicode_ci'),
               type_=sa.Text(length=16777215),
               existing_nullable=False)
        batch_op.alter_column('summary_text',
               existing_type=mysql.MEDIUMTEXT(collation='utf8mb4_unicode_ci'),
               type_=sa.Text(length=16777215),
               existing_nullable=False)
        batch_op.drop_index('ft_keywords', mysql_prefix='FULLTEXT')
        batch_op.drop_index('ft_summary', mysql_prefix='FULLTEXT')
        batch_op.drop_index('idx_timestamp')
        batch_op.drop_column('level')
        batch_op.drop_column('focus_areas')
        batch_op.drop_column('language_style')
        batch_op.drop_column('style')
        batch_op.drop_column('format')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('idx_role')
        batch_op.drop_index('idx_username')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('idx_username', ['username'], unique=False)
        batch_op.create_index('idx_role', ['role'], unique=False)

    with op.batch_alter_table('summaries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('format', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20), nullable=True))
        batch_op.add_column(sa.Column('style', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20), nullable=True))
        batch_op.add_column(sa.Column('language_style', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20), nullable=True))
        batch_op.add_column(sa.Column('focus_areas', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True))
        batch_op.add_column(sa.Column('level', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20), nullable=True))
        batch_op.create_index('idx_timestamp', ['timestamp'], unique=False)
        batch_op.create_index('ft_summary', ['summary_text'], unique=False, mysql_prefix='FULLTEXT')
        batch_op.create_index('ft_keywords', ['keywords'], unique=False, mysql_prefix='FULLTEXT')
        batch_op.alter_column('summary_text',
               existing_type=sa.Text(length=16777215),
               type_=mysql.MEDIUMTEXT(collation='utf8mb4_unicode_ci'),
               existing_nullable=False)
        batch_op.alter_column('original_text',
               existing_type=sa.Text(length=16777215),
               type_=mysql.MEDIUMTEXT(collation='utf8mb4_unicode_ci'),
               existing_nullable=False)
        batch_op.drop_column('critical')
        batch_op.drop_column('structure')
        batch_op.drop_column('emphasis')
        batch_op.drop_column('audience')
        batch_op.drop_column('purpose')

    with op.batch_alter_table('file_mappings', schema=None) as batch_op:
        batch_op.create_index('idx_system_filename', ['system_filename'], unique=False)
        batch_op.create_index('idx_summary_id', ['summary_id'], unique=False)

    with op.batch_alter_table('file_chunks', schema=None) as batch_op:
        batch_op.create_index('idx_document_chunk', ['document_id', 'chunk_index'], unique=False)
        batch_op.alter_column('chunk_data',
               existing_type=sa.LargeBinary(length=10485760),
               type_=mysql.MEDIUMBLOB(),
               existing_nullable=False)

    with op.batch_alter_table('document_summaries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('document_summaries_ibfk_1', 'users', ['user_id'], ['id'], ondelete='SET NULL')
        batch_op.create_index('idx_user_id', ['user_id'], unique=False)
        batch_op.create_index('idx_file_hash', ['file_hash'], unique=False)
        batch_op.create_index('idx_created_at', ['created_at'], unique=False)
        batch_op.create_index('ft_summary', ['summary_text'], unique=False, mysql_prefix='FULLTEXT')
        batch_op.create_index('ft_keywords', ['keywords'], unique=False, mysql_prefix='FULLTEXT')
        batch_op.alter_column('summary_vectors',
               existing_type=sa.LargeBinary(length=16777215),
               type_=mysql.MEDIUMBLOB(),
               existing_nullable=True)
        batch_op.alter_column('content_vectors',
               existing_type=sa.LargeBinary(length=16777215),
               type_=mysql.MEDIUMBLOB(),
               existing_nullable=True)
        batch_op.alter_column('file_content',
               existing_type=sa.LargeBinary(length=16777215),
               type_=mysql.MEDIUMBLOB(),
               existing_nullable=True)
        batch_op.alter_column('summary_text',
               existing_type=sa.Text(length=16777215),
               type_=mysql.MEDIUMTEXT(collation='utf8mb4_unicode_ci'),
               existing_nullable=True)
        batch_op.alter_column('original_text',
               existing_type=sa.Text(length=16777215),
               type_=mysql.MEDIUMTEXT(collation='utf8mb4_unicode_ci'),
               existing_nullable=True)

    op.create_table('system_settings',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('setting_key', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=False),
    sa.Column('setting_value', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=False),
    sa.Column('setting_type', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=False),
    sa.Column('description', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('system_settings', schema=None) as batch_op:
        batch_op.create_index('setting_key', ['setting_key'], unique=True)
        batch_op.create_index('idx_setting_key', ['setting_key'], unique=False)

    op.create_table('search_history',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('document_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('query_text', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False),
    sa.Column('search_type', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['document_summaries.id'], name='search_history_ibfk_2', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='search_history_ibfk_1', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('search_history', schema=None) as batch_op:
        batch_op.create_index('idx_user_document', ['user_id', 'document_id'], unique=False)

    # ### end Alembic commands ###
