"""add is_chunked and total_chunks fields

Revision ID: 2cdb0cde1d7f
Revises: 4752af7743f4
Create Date: 2025-02-09 13:55:35.964343

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2cdb0cde1d7f'
down_revision = '4752af7743f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document_summaries', schema=None) as batch_op:
        batch_op.alter_column('original_text',
               existing_type=mysql.LONGTEXT(collation='utf8mb4_unicode_ci'),
               type_=sa.Text(length=16777215),
               existing_nullable=True)
        batch_op.alter_column('summary_text',
               existing_type=mysql.LONGTEXT(collation='utf8mb4_unicode_ci'),
               type_=sa.Text(length=16777215),
               existing_nullable=True)
        batch_op.alter_column('file_content',
               existing_type=mysql.MEDIUMBLOB(),
               type_=sa.LargeBinary(length=16777215),
               existing_nullable=True)
        batch_op.drop_column('chunk_data')

    with op.batch_alter_table('file_chunks', schema=None) as batch_op:
        batch_op.alter_column('chunk_data',
               existing_type=mysql.MEDIUMBLOB(),
               type_=sa.LargeBinary(length=10485760),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file_chunks', schema=None) as batch_op:
        batch_op.alter_column('chunk_data',
               existing_type=sa.LargeBinary(length=10485760),
               type_=mysql.MEDIUMBLOB(),
               existing_nullable=False)

    with op.batch_alter_table('document_summaries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('chunk_data', mysql.MEDIUMBLOB(), nullable=True))
        batch_op.alter_column('file_content',
               existing_type=sa.LargeBinary(length=16777215),
               type_=mysql.MEDIUMBLOB(),
               existing_nullable=True)
        batch_op.alter_column('summary_text',
               existing_type=sa.Text(length=16777215),
               type_=mysql.LONGTEXT(collation='utf8mb4_unicode_ci'),
               existing_nullable=True)
        batch_op.alter_column('original_text',
               existing_type=sa.Text(length=16777215),
               type_=mysql.LONGTEXT(collation='utf8mb4_unicode_ci'),
               existing_nullable=True)

    # ### end Alembic commands ###
