"""add file_hash field

Revision ID: 4752af7743f4
Revises: 
Create Date: 2025-02-09 11:57:07.511419

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4752af7743f4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document_summaries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_hash', sa.String(length=32), nullable=True))
        batch_op.alter_column('original_text',
               existing_type=mysql.LONGTEXT(collation='utf8mb4_unicode_ci'),
               type_=sa.Text(length=16777215),
               existing_nullable=True)
        batch_op.alter_column('summary_text',
               existing_type=mysql.LONGTEXT(collation='utf8mb4_unicode_ci'),
               type_=sa.Text(length=16777215),
               existing_nullable=True)
        batch_op.alter_column('file_content',
               existing_type=mysql.MEDIUMBLOB(),
               type_=sa.LargeBinary(length=16777215),
               existing_nullable=True)
        batch_op.alter_column('chunk_data',
               existing_type=mysql.MEDIUMBLOB(),
               type_=sa.LargeBinary(length=16777215),
               existing_nullable=True)

    with op.batch_alter_table('file_chunks', schema=None) as batch_op:
        batch_op.alter_column('chunk_data',
               existing_type=mysql.MEDIUMBLOB(),
               type_=sa.LargeBinary(length=10485760),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file_chunks', schema=None) as batch_op:
        batch_op.alter_column('chunk_data',
               existing_type=sa.LargeBinary(length=10485760),
               type_=mysql.MEDIUMBLOB(),
               existing_nullable=False)

    with op.batch_alter_table('document_summaries', schema=None) as batch_op:
        batch_op.alter_column('chunk_data',
               existing_type=sa.LargeBinary(length=16777215),
               type_=mysql.MEDIUMBLOB(),
               existing_nullable=True)
        batch_op.alter_column('file_content',
               existing_type=sa.LargeBinary(length=16777215),
               type_=mysql.MEDIUMBLOB(),
               existing_nullable=True)
        batch_op.alter_column('summary_text',
               existing_type=sa.Text(length=16777215),
               type_=mysql.LONGTEXT(collation='utf8mb4_unicode_ci'),
               existing_nullable=True)
        batch_op.alter_column('original_text',
               existing_type=sa.Text(length=16777215),
               type_=mysql.LONGTEXT(collation='utf8mb4_unicode_ci'),
               existing_nullable=True)
        batch_op.drop_column('file_hash')

    # ### end Alembic commands ###
