"""change file storage to filesystem

Revision ID: 5e355880dfa4
Revises: 0f9527abd1fe
Create Date: 2025-02-04 21:12:06.668571

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5e355880dfa4'
down_revision = '0f9527abd1fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document_summaries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_path', sa.String(length=255), nullable=True))
        batch_op.alter_column('summary_text',
               existing_type=mysql.LONGTEXT(collation='utf8mb4_unicode_ci'),
               type_=sa.Text(length=4294967295),
               existing_nullable=False)
        batch_op.alter_column('original_text',
               existing_type=mysql.LONGTEXT(collation='utf8mb4_unicode_ci'),
               type_=sa.Text(length=4294967295),
               existing_nullable=False)
        batch_op.drop_column('file_content')
        batch_op.drop_column('analysis_text')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document_summaries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('analysis_text', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True))
        batch_op.add_column(sa.Column('file_content', mysql.LONGBLOB(), nullable=True))
        batch_op.alter_column('original_text',
               existing_type=sa.Text(length=4294967295),
               type_=mysql.LONGTEXT(collation='utf8mb4_unicode_ci'),
               existing_nullable=False)
        batch_op.alter_column('summary_text',
               existing_type=sa.Text(length=4294967295),
               type_=mysql.LONGTEXT(collation='utf8mb4_unicode_ci'),
               existing_nullable=False)
        batch_op.drop_column('file_path')

    # ### end Alembic commands ###
